// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/auction.proto

package auction

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContractNet_RequestBid_FullMethodName = "/auction.ContractNet/RequestBid"
)

// ContractNetClient is the client API for ContractNet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The ContractNet service for resource bidding
type ContractNetClient interface {
	// Request a bid for a task
	RequestBid(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*BidResponse, error)
}

type contractNetClient struct {
	cc grpc.ClientConnInterface
}

func NewContractNetClient(cc grpc.ClientConnInterface) ContractNetClient {
	return &contractNetClient{cc}
}

func (c *contractNetClient) RequestBid(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*BidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BidResponse)
	err := c.cc.Invoke(ctx, ContractNet_RequestBid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContractNetServer is the server API for ContractNet service.
// All implementations must embed UnimplementedContractNetServer
// for forward compatibility.
//
// The ContractNet service for resource bidding
type ContractNetServer interface {
	// Request a bid for a task
	RequestBid(context.Context, *TaskRequest) (*BidResponse, error)
	mustEmbedUnimplementedContractNetServer()
}

// UnimplementedContractNetServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContractNetServer struct{}

func (UnimplementedContractNetServer) RequestBid(context.Context, *TaskRequest) (*BidResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestBid not implemented")
}
func (UnimplementedContractNetServer) mustEmbedUnimplementedContractNetServer() {}
func (UnimplementedContractNetServer) testEmbeddedByValue()                     {}

// UnsafeContractNetServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContractNetServer will
// result in compilation errors.
type UnsafeContractNetServer interface {
	mustEmbedUnimplementedContractNetServer()
}

func RegisterContractNetServer(s grpc.ServiceRegistrar, srv ContractNetServer) {
	// If the following call panics, it indicates UnimplementedContractNetServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContractNet_ServiceDesc, srv)
}

func _ContractNet_RequestBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractNetServer).RequestBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractNet_RequestBid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractNetServer).RequestBid(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContractNet_ServiceDesc is the grpc.ServiceDesc for ContractNet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContractNet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auction.ContractNet",
	HandlerType: (*ContractNetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestBid",
			Handler:    _ContractNet_RequestBid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/auction.proto",
}
