// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/auction.proto

package auction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Data sent by the Manager Agent
type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	CpuReqNorm    float64                `protobuf:"fixed64,2,opt,name=cpu_req_norm,json=cpuReqNorm,proto3" json:"cpu_req_norm,omitempty"` // Normalized CPU requirement (0.0 to 1.0)
	RamReqNorm    float64                `protobuf:"fixed64,3,opt,name=ram_req_norm,json=ramReqNorm,proto3" json:"ram_req_norm,omitempty"` // Normalized RAM requirement (0.0 to 1.0)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_proto_auction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskRequest) GetCpuReqNorm() float64 {
	if x != nil {
		return x.CpuReqNorm
	}
	return 0
}

func (x *TaskRequest) GetRamReqNorm() float64 {
	if x != nil {
		return x.RamReqNorm
	}
	return 0
}

// Data returned by the Node Agent
type BidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	F1CpuFrag     float64                `protobuf:"fixed64,2,opt,name=f1_cpu_frag,json=f1CpuFrag,proto3" json:"f1_cpu_frag,omitempty"` // Fragmentation f1 (CPU)
	F3RamFrag     float64                `protobuf:"fixed64,3,opt,name=f3_ram_frag,json=f3RamFrag,proto3" json:"f3_ram_frag,omitempty"` // Fragmentation f3 (RAM)
	Accepted      bool                   `protobuf:"varint,4,opt,name=accepted,proto3" json:"accepted,omitempty"`                       // Whether the node can host the task
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidResponse) Reset() {
	*x = BidResponse{}
	mi := &file_proto_auction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResponse) ProtoMessage() {}

func (x *BidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResponse.ProtoReflect.Descriptor instead.
func (*BidResponse) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{1}
}

func (x *BidResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *BidResponse) GetF1CpuFrag() float64 {
	if x != nil {
		return x.F1CpuFrag
	}
	return 0
}

func (x *BidResponse) GetF3RamFrag() float64 {
	if x != nil {
		return x.F3RamFrag
	}
	return 0
}

func (x *BidResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_proto_auction_proto protoreflect.FileDescriptor

const file_proto_auction_proto_rawDesc = "" +
	"\n" +
	"\x13proto/auction.proto\x12\aauction\"j\n" +
	"\vTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12 \n" +
	"\fcpu_req_norm\x18\x02 \x01(\x01R\n" +
	"cpuReqNorm\x12 \n" +
	"\fram_req_norm\x18\x03 \x01(\x01R\n" +
	"ramReqNorm\"\x82\x01\n" +
	"\vBidResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1e\n" +
	"\vf1_cpu_frag\x18\x02 \x01(\x01R\tf1CpuFrag\x12\x1e\n" +
	"\vf3_ram_frag\x18\x03 \x01(\x01R\tf3RamFrag\x12\x1a\n" +
	"\baccepted\x18\x04 \x01(\bR\baccepted2G\n" +
	"\vContractNet\x128\n" +
	"\n" +
	"RequestBid\x12\x14.auction.TaskRequest\x1a\x14.auction.BidResponseB6Z4github.com/diego/k8s-agentic-scheduler/proto/auctionb\x06proto3"

var (
	file_proto_auction_proto_rawDescOnce sync.Once
	file_proto_auction_proto_rawDescData []byte
)

func file_proto_auction_proto_rawDescGZIP() []byte {
	file_proto_auction_proto_rawDescOnce.Do(func() {
		file_proto_auction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auction_proto_rawDesc), len(file_proto_auction_proto_rawDesc)))
	})
	return file_proto_auction_proto_rawDescData
}

var file_proto_auction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_auction_proto_goTypes = []any{
	(*TaskRequest)(nil), // 0: auction.TaskRequest
	(*BidResponse)(nil), // 1: auction.BidResponse
}
var file_proto_auction_proto_depIdxs = []int32{
	0, // 0: auction.ContractNet.RequestBid:input_type -> auction.TaskRequest
	1, // 1: auction.ContractNet.RequestBid:output_type -> auction.BidResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_auction_proto_init() }
func file_proto_auction_proto_init() {
	if File_proto_auction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auction_proto_rawDesc), len(file_proto_auction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auction_proto_goTypes,
		DependencyIndexes: file_proto_auction_proto_depIdxs,
		MessageInfos:      file_proto_auction_proto_msgTypes,
	}.Build()
	File_proto_auction_proto = out.File
	file_proto_auction_proto_goTypes = nil
	file_proto_auction_proto_depIdxs = nil
}
